version: '3.1'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      # Please decomment if you want to expose ports to the host
      #- "8083:8083"
      #- "8086:8086"
      #- "8090:8090"
    environment:
      INFLUXDB_DB: "linky"
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      # Data persistency
      # sudo mkdir -p ./data/influxdb
      # sudo mkdir -p ./data/docker-entrypoint-initdb.d
      - "./data/influxdb:/var/lib/influxdb"
      - "./data/docker-entrypoint-initdb.d/linky.iql:/docker-entrypoint-initdb.d/linky.iql"

  linky:
    build: docker/linky/
    container_name: linky
    stdin_open: true
    tty: true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - "./data/grafana:/var/lib/grafana"
